config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    resource :checkout, :controller=>"checkout" do
      member do
        get :payu_in_checkout
        get :payu_in_payment
        get :payu_in_confirm
        get :payu_in_finish
      end
    end
  end

  match "/payment_confirmed" => "checkout#gateway_callback", :method => :post, :as=> 'payment_callback'

  namespace :admin do
    resources :orders do
      resources :payu_in_payments, :member => {:capture => :get, :refund => :any}, :has_many => [:txns]
    end
  end
end

app/models/gateway/payu_in.rb
class Gateway::PayuIn < Gateway
  preference :merchant_id, :string
	preference :salt, :string
	preference :url, :string
  
  def provider_class
		PayuInGateway
  end	

  def payment_page_url(order)
    payu_in_payment_url(order)
  end
  
  def external_payment_url
    self.url
  end
end

app/models/payu_in_gateway.rb
require 'digest/sha2'

class PayuInGateway
  def initialize(hash)
    @opts = hash
  end
  
  def external_payment_url
    "#{@opts[:url]}/_payment.php"
  end
  
  def merchant_id
    @opts[:merchant_id]
  end

  def salt
    @opts[:salt]
  end
  
  def hash(order, payment_method_id)
    Digest::SHA512.hexdigest("#{self.merchant_id}|#{order.id}|#{order.total.to_i}|#{order.number}|#{order.bill_address.firstname}|#{order.user.email}|#{payment_method_id}||||||||||#{self.salt}")
  end
end

app/models/payu_payment.rb
class PayuPayment < ActiveRecord::Base
  has_many :payments, :as => :source
  
  def self.new_from(params)
    PayuPayment.new(
    :payment_id=> params['mihpayid'],
    :mode => params['mode'],
    :status => params['status'],
    :key => params['key'],
    :transaction_id=> params['tnxid'],
    :amount => BigDecimal.new(params['amount']).to_f,
    :discount=> params['discount'],
    :json=> params.to_json) 
  end
  
  def process!(payment)
  end
end

app/controllers/checkout_controller_decorator.rb
CheckoutController.class_eval do
  include Spree::PayuIn
end

app/views/payment/gateway/_payu_form.html.erb
<%= form_tag(@gateway.external_payment_url, :method=>:post) do %>
  <%= hidden_field_tag 'key', @gateway.merchant_id %>
  <%= hidden_field_tag 'txnid', "#{@order.id}" %>
  <%= hidden_field_tag 'amount', @order.total.to_f %>
  <%= hidden_field_tag 'productinfo', @order.number %>
  <%= hidden_field_tag 'firstname', @order.bill_address.firstname %>
  <%= hidden_field_tag 'Lastname', @order.bill_address.lastname %>
  <%= hidden_field_tag 'address1', @order.bill_address.address1 %>
  <%= hidden_field_tag 'address2', @order.bill_address.address2 %>
  <%= hidden_field_tag 'City', @order.bill_address.city %>
  <%= hidden_field_tag 'State', @order.bill_address.state.name %>
  <%= hidden_field_tag 'Country', @order.bill_address.country.name %>
  <%= hidden_field_tag 'Zipcode', @order.bill_address.zipcode %>
  <%= hidden_field_tag 'email', @order.user.email %>
  <%= hidden_field_tag 'phone', @order.bill_address.phone %>
  <%= hidden_field_tag 'surl', payment_callback_url %>
  <%= hidden_field_tag 'Furl', payment_callback_url(:status=>'failed') %>
  <%= hidden_field_tag 'curl', payment_callback_url(:status=> 'canceled') %>
  <%= hidden_field_tag 'udf1', params[:payment_method_id] %>
  <%= hidden_field_tag 'Hash', @gateway.hash(@order, params[:payment_method_id]) %>
  <%= submit_tag 'Proceed to payment' %>
<% end %>

app/views/payment/gateway/payu_in_payment.html.erb
<h1>Proceed to PayU Payment Gateway</h1>

<h5>You will now be redirected to PayU's payment gateway page.</h5>

<%= render :partial => 'payment/gateway/payu_form' %>